from .semantic_post_processing  import get_semantic_segmentation
from .wholistic_post_processing import get_wholistic_segmentation
from .semantic_calibration_post_processing import get_semantic_calibration_segmentation, get_semantic_msp_segmentation, get_semantic_maxlogit_segmentation
from .semantic_anomaly_post_processing     import get_semantic_anomaly_segmentation
